import os
st=[{"oldvalue":"LABEL_SEARCHDATAELEMENTGROUP_TTT","newvalue":"Write DataElement group name here"},
{"oldvalue":"LABEL_ORGANISATION_UNIT_GROUPS","newvalue":" Organization units groups"},
{"oldvalue":"OBJ_ORGANISATIONUNITGROUPSSETS","newvalue":"Organisation unit groups sets"},
{"oldvalue":"LABEL_CATEGORYOPTIONGROUP_TTT","newvalue":"Write category option group name here"},
{"oldvalue":"LABEL_NUMBER_OBJECT_NOUPDATED","newvalue":"Number of objects don't updated"},
{"oldvalue":"LABEL_SEARCHPROGRAMORDATASET","newvalue":"Filter objects related with:"},
{"oldvalue":"LABEL_SEARCHDATAELEMENTGROUP","newvalue":"DataElement Groups"},
{"oldvalue":"LABEL_SEARCHPROGRAMSTAGE_TTT","newvalue":" Write programStage name here"},
{"oldvalue":"LABEL_CATEGORYOPGROUPSET_TTT","newvalue":"Write category option group set name here"},
{"oldvalue":"OBJ_CATEGORYOPTIONGROUPSETS","newvalue":"Category option group sets"},
{"oldvalue":"MESSAGE_ERROR_SELECT_OBJECT","newvalue":" Select at least one object, user or group"},
{"oldvalue":"MESSAGE_DISABLED_DATABUTTON","newvalue":"Not available for this type of object"},
{"oldvalue":"LABEL_NUMBER_OBJECT_UPDATED","newvalue":"Number of objects updated"},
{"oldvalue":"OBJ_ORGANISATIONUNITGROUPS","newvalue":"Organisation unit groups"},
{"oldvalue":"LABEL_WISHDELETEUSERGROUPS","newvalue":"Do you want to delete user groups?"},
{"oldvalue":"LABEL_SEARCHUSERGROUP_TTT","newvalue":"Write user group name here"},
{"oldvalue":"LABEL_SEARCHINDICATOR_TTT","newvalue":"Write program indicator name here"},
{"oldvalue":"LABEL_CATEGORYOPTIONGROUP","newvalue":"Category option group"},
{"oldvalue":"LABEL_INDICATORGROUPS_TTT","newvalue":"Write indicator group here"},
{"oldvalue":"OBJ_DATAELEMENTGROUPSETS","newvalue":"Data Element Groups Sets"},
{"oldvalue":"OBJ_CATEGORYOPTIONCOMBOS","newvalue":"Category option combos"},
{"oldvalue":"OBJ_CATEGORYOPTIONGROUPS","newvalue":"Category Option Groups"},
{"oldvalue":"LABEL_SEARCHPROGRAMSTAGE","newvalue":"Program Stage"},
{"oldvalue":"LABEL_CATEGORYOPGROUPSET","newvalue":"Category option group set"},
{"oldvalue":"LABEL_INDICATORS_GROUPS","newvalue":" Indicators groups"},
{"oldvalue":"LABEL_UPDATEPERMISSIONS","newvalue":"Update permissions"},
{"oldvalue":"LABEL_SEARCHDATASET_TTT","newvalue":"Write dataset name here"},
{"oldvalue":"LABEL_SEARCHPROGRAM_TTT","newvalue":" Write program name here"},
{"oldvalue":"LABEL_CATEGORYCOMBO_TTT","newvalue":"Write category Combo name here"},
{"oldvalue":"LABEL_DELETEUSERGROUPS","newvalue":"Delete user groups"},
{"oldvalue":"LABEL_SEARCHCATEGORIES","newvalue":"categories"},
{"oldvalue":"LABEL_SEARCHUSERGROUP2","newvalue":"Name"},
{"oldvalue":"OBJ_TRACKEDENTITYTYPES","newvalue":"Tracked entity type"},
{"oldvalue":"LABEL_LIST_PERMISSION","newvalue":" Object List of type"},
{"oldvalue":"LABEL_NORESULTSFOUND ","newvalue":"NO RESULTS FOUND"},
{"oldvalue":"LABEL_FINDOPTIONS_SUB","newvalue":"Filter objects according to the type selected"},
{"oldvalue":"LABEL_KEEPPERMISSIONS","newvalue":"Keep permissions"},
{"oldvalue":"TAB_WHATDOYOUWANTTODO","newvalue":"What do you want to do?"},
{"oldvalue":"LABEL_SEARCHUSERGROUP","newvalue":"User groups"},
{"oldvalue":"OBJ_PROGRAMINDOCATORS","newvalue":"Programs Indicators"},
{"oldvalue":"TABLE_METADATA_ACCESS","newvalue":" METADATA"},
{"oldvalue":"LABEL_SEARCHINDICATOR","newvalue":"Program indicators"},
{"oldvalue":"LABEL_INDICATORGROUPS","newvalue":"Indicator group"},
{"oldvalue":"OPTION_EXTERNALACCESS","newvalue":"Setting external Access"},
{"oldvalue":"LBL_CATEGORY_OPTIONS","newvalue":" Category Options"},
{"oldvalue":"OBJ_DATAELEMENTGROUP","newvalue":"Data Element Groups"},
{"oldvalue":"OBJ_INDICATORSGROUPS","newvalue":"Indicator groups"},
{"oldvalue":"LABEL_USERPERMISIONS","newvalue":"User permision"},
{"oldvalue":"TAB_ASIGNPERMISSIONS","newvalue":"Assign permisions"},
{"oldvalue":"LABEL_EXTERNALACCESS","newvalue":"External"},
{"oldvalue":"LABEL_SEARCHPROGRAMS","newvalue":"Program"},
{"oldvalue":"TABLE_EXTERNALACCESS","newvalue":"External Access"},
{"oldvalue":"LABEL_SEARCHUSER_TTT","newvalue":"write user name here"},
{"oldvalue":"LABEL_OUGROUPSET_TTT","newvalue":"Write name here"},
{"oldvalue":"CN_SUBTITLE_METADATA","newvalue":"METADATA: privileges related to access"},
{"oldvalue":"OBJ_CATEGORYOPTIONS","newvalue":"Category options"},
{"oldvalue":"OBJ_INDICATORSTYPES","newvalue":" Indicator types"},
{"oldvalue":"LABEL_SELECTEDITEMS","newvalue":"Selected items"},
{"oldvalue":"LABEL_SELECTDATASET","newvalue":" Select data set"},
{"oldvalue":"LABEL_SEARCHDATASET","newvalue":"Data Set"},
{"oldvalue":"LABEL_SELECTPROGRAM","newvalue":" Select program"},
{"oldvalue":"LABEL_SEARCHPROGRAM","newvalue":"Program"},
{"oldvalue":"LABEL_UPDATE_TOGGLE","newvalue":"Update Mode"},
{"oldvalue":"LABEL_CATEGORYCOMBO","newvalue":"Category Combo"},
{"oldvalue":"OPTION_PUBLICACCESS","newvalue":"Setting public Access"},
{"oldvalue":"LABEL_LIST_OBJECTS","newvalue":" Objects type List"},
{"oldvalue":"LBL_CATEGORY_COMBO","newvalue":" CategoryCombo"},
{"oldvalue":"LBLSELECT_ELEMENTS","newvalue":" Select Elements"},
{"oldvalue":"LABEL_PUBLICACCESS","newvalue":"Public Access"},
{"oldvalue":"TABLE_PUBLICACCESS","newvalue":"Public Access"},
{"oldvalue":"TABLE_SHARINGGROUP","newvalue":"Groups"},
{"oldvalue":"TITLE_SEARCH_GROUP","newvalue":"Add users and user groups"},
{"oldvalue":"LABEL_CATEGORY_TTT","newvalue":"Write category name here"},
{"oldvalue":"LBL_DATA_ELEMENTS","newvalue":" DataElements"},
{"oldvalue":"LABEL_OPTION_SETS","newvalue":" Option Sets"},
{"oldvalue":"OBJ_CATEGORYCOMBO","newvalue":"Category Combo"},
{"oldvalue":"TAB_ASIGNELEMENTS","newvalue":"Assign User Groups"},
{"oldvalue":"LABEL_PERMISSIONS","newvalue":"Permissions"},
{"oldvalue":"LABEL_SELECTGROUP","newvalue":" Select group"},
{"oldvalue":"LABEL_SEARCHGROUP","newvalue":"group"},
{"oldvalue":"LABEL_FINDOPTIONS","newvalue":"Filter"},
{"oldvalue":"BUTTON_DELETE_ALL","newvalue":"Delete all user groups"},
{"oldvalue":"OBJ_TRKATTRIBUTES","newvalue":"Tracker Attributes"},
{"oldvalue":"TABLE_SHARINGUSER","newvalue":"Users"},
{"oldvalue":"TABLE_DATA_ACCESS","newvalue":" DATA"},
{"oldvalue":"LABEL_NOVALUE_TTT","newvalue":"Select one filter option"},
{"oldvalue":"SUBTITLE_STRATEGY","newvalue":"Strategy to save Sharing Setting to all object selected"},
{"oldvalue":"LABEL_INDICATORS","newvalue":" Indicators"},
{"oldvalue":"LABEL_CONVENTION","newvalue":"Convencion of colors"},
{"oldvalue":"LABEL_SEARCHNAME","newvalue":" Search by name"},
{"oldvalue":"BUTTON_CLEAR_ALL","newvalue":"Clear all"},
{"oldvalue":"OBJ_EVENTREPORTS","newvalue":"Events Reports"},
{"oldvalue":"OBJ_REPORTTABLES","newvalue":"Pivot Tables"},
{"oldvalue":"OBJ_RELATIONSHIP","newvalue":"Relationship type"},
{"oldvalue":"OBJ_PROGRAMSTAGE","newvalue":"Program Stages"},
{"oldvalue":"LABEL_SEARCHUSER","newvalue":"Users"},
{"oldvalue":"LABEL_OUGROUPSET","newvalue":"OU group set"},
{"oldvalue":"CN_SUBTITLE_DATA","newvalue":"DATA: Privileges related to data registration and access"},
{"oldvalue":"OPTION_OVERWRITE","newvalue":"Overwrite Sharing settings"},
{"oldvalue":"LABEL_EDIT_VIEW","newvalue":" Edit - View"},
{"oldvalue":"OBJ_DATAELEMENT","newvalue":"Data Elements"},
{"oldvalue":"LABEL_USERGROUP","newvalue":"User group"},
{"oldvalue":"LABEL_READWRITE","newvalue":"Can Edit"},
{"oldvalue":"LABEL_SELECTALL","newvalue":"Apply to all user Groups Firtered"},
{"oldvalue":"OBJ_EVENTCHARTS","newvalue":"Events charts"},
{"oldvalue":"TABLE_USER_NAME","newvalue":" User"},
{"oldvalue":"SUBTITLE_PUBLIC","newvalue":"Setting public and external access to all object selected"},
{"oldvalue":"LABEL_DATASETS","newvalue":" Data sets"},
{"oldvalue":"OBJ_CATEGORIES","newvalue":"Categories"},
{"oldvalue":"OBJ_INDICATORS","newvalue":"Indicators"},
{"oldvalue":"OBJ_OPTIONSETS","newvalue":"Option sets"},
{"oldvalue":"OBJ_USERGROUPS","newvalue":"User Groups"},
{"oldvalue":"LABEL_SEARCHBY","newvalue":"Search by"},
{"oldvalue":"OBJ_LEGENDSETS","newvalue":"Legend Sets"},
{"oldvalue":"OBJ_DASHBOARDS","newvalue":"Dashboards"},
{"oldvalue":"BTN_REMOVE_ALL","newvalue":" REMOVE All"},
{"oldvalue":"LABEL_CATEGORY","newvalue":"Category"},
{"oldvalue":"OBJ_USERROLES","newvalue":"User Roles"},
{"oldvalue":"TAB_VIEW_MODE","newvalue":"Individual mode"},
{"oldvalue":"TAB_EDIT_MODE","newvalue":"Bulk mode"},
{"oldvalue":"OBJ_CONSTANTS","newvalue":"Constants"},
{"oldvalue":"BTN_ASIGN_ALL","newvalue":" ASING All"},
{"oldvalue":"LABEL_NOVALUE","newvalue":"<No value>"},
{"oldvalue":"OBJ_DATASETS","newvalue":"Data sets"},
{"oldvalue":"LABEL_SEARCH","newvalue":"Search"},
{"oldvalue":"BUTTON_CLEAR","newvalue":"Clear"},
{"oldvalue":"OBJ_PROGRAMS","newvalue":"Programs"},
{"oldvalue":"OBJ_SQLVIEWS","newvalue":"SQL Viev"},
{"oldvalue":"LABEL_ASIGN","newvalue":" Assign"},
{"oldvalue":"LABEL_ASIGN","newvalue":"Assign"},
{"oldvalue":"TAB_OBJECTS","newvalue":"Objects"},
{"oldvalue":"LABEL_CLOSE","newvalue":"Close"},
{"oldvalue":"OPTION_KEEP","newvalue":"Merge with current Sharing settings"},
{"oldvalue":"TITLE_APPS","newvalue":"SHARING SETTING version 1.5"},
{"oldvalue":"LABEL_EDIT","newvalue":" Edit"},
{"oldvalue":"LABEL_NONE","newvalue":" None"},
{"oldvalue":"LABEL_ITEM","newvalue":" Items"},
{"oldvalue":"LABEL_USER","newvalue":"User"},
{"oldvalue":"LABEL_READ","newvalue":"Can View"},
{"oldvalue":"LABEL_NONE","newvalue":"None"},
{"oldvalue":"LABEL_CODE","newvalue":"Code"},
{"oldvalue":"OBJ_CHARTS","newvalue":"Agreggate chart"},
{"oldvalue":"TABLE_NAME","newvalue":"Name"},
{"oldvalue":"BTN_CANCEL","newvalue":"CANCEL"},
{"oldvalue":"BTN_FINISH","newvalue":"FINISH"},
{"oldvalue":"TAB_USERS","newvalue":"Watch Users"},
{"oldvalue":"LABEL_YES","newvalue":"Yes"},
{"oldvalue":"NO_ACCESS","newvalue":"No Access"},
{"oldvalue":"BTN_CLOSE","newvalue":"CLOSE"},
{"oldvalue":"LABEL_NO","newvalue":"No"},
{"oldvalue":"OBJ_MAPS","newvalue":"Maps"},
{"oldvalue":"CAN_EDIT","newvalue":"Can find, view and edit"},
{"oldvalue":"CAN_VIEW","newvalue":"Can find and view"},
{"oldvalue":"CN_CLOSE","newvalue":"Close"},
{"oldvalue":"CN_TITLE","newvalue":"Conventions"},
{"oldvalue":"BTN_BACK","newvalue":"BACK"},
{"oldvalue":"BTN_NEXT","newvalue":" NEXT"},
{"oldvalue":"BTN_SAVE","newvalue":"SAVE SETTING"},
{"oldvalue":"STEP_1","newvalue":"Select the Object"},
{"oldvalue":"STEP_2","newvalue":"Select the user and/or groups"},
{"oldvalue":"STEP_3","newvalue":"Define the strategy to setting"},
{"oldvalue":"STEP_4","newvalue":"Summary"}
]
for dname, dirs, files in os.walk("src2"):
    for fname in files:
        fpath = os.path.join(dname, fname)
        print(fpath)
        with open(fpath) as f:   
            s = f.read()
        for string in st:
            s = s.replace(string["oldvalue"], string["newvalue"])
        with open(fpath, "w") as f:
            f.write(s)